os:
  - osx
language: 
  - objective-c
compiler:
  - clang
notifications:
  slack: spuc:VfvBwrKcCRGX7RWcZBIfXFBr
before_install:
  - brew update
install:
  - brew install qt5
before_script:
  - mkdir build
  - cd build
  - cmake ..
script: make
