dist: trusty
language:  cpp
compiler : gcc
notifications:
  slack: spuc:VfvBwrKcCRGX7RWcZBIfXFBr
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq cmake
  - sudo apt-get install -qq python-dev 
  - sudo apt-get install -qq qt5-default
before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5
script: make
