	- sudo false
language: 
  - cpp 
compiler:
  - clang
install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
before_script:
  - mkdir build
  - cd build
  - cmake ..
script: make
